Repository FE-team1/coworkers, pull requests merged in 2025-05, with the labels that each got.

#67 Style : update className
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateWiseTaskLists.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/CreateTaskListModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModalContent.tsx
  src/app/(content-layout)/[groupId]/tasklist/page.tsx
  src/app/(content-layout)/myhistory/page.tsx
Labels: chore, style

#68 Fix : 한 페이지에 서로 다른 Modal을 띄우지 못하는 오류 해결
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/CreateTaskListModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModalContent.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModalPopUp.tsx
  src/app/layout.tsx
  src/components/common/modal/core/ModalContext.tsx
  src/components/common/modal/core/ModalPortal.tsx
  src/components/common/modal/core/ModalProvider.tsx
  src/components/common/modal/ui/ModalCloseButton.tsx
  src/components/common/modal/ui/ModalOverlay.tsx
  src/components/common/modal/ui/ModalTrigger.tsx
Labels: fix

#66 Feature : 자유게시판 댓글 컴포넌트 UI 구현
  src/components/comment/index.tsx
  src/components/comment/types.d.ts
Labels: feat

#63 Feat : 계정 관리 페이지 ui 생성
  public/icons/secession.svg
  src/app/globals.css
  src/app/mypage/page.tsx
  src/components/layout/gnb/Header.tsx
  src/components/layout/gnb/SideMenu.tsx
  src/components/mypage-modal/DeleteAccountModal.tsx
Labels: feat

#70 Feat : create group data fetching
  src/app/(form-layout)/addgroup/page.tsx
  src/app/(form-layout)/addteam/page.tsx
  src/app/(form-layout)/editgroup/page.tsx
  src/components/common/formField/compound/FileInput.tsx
  src/components/common/formField/compound/ImageUploader.tsx
  src/components/common/formField/hook/useFieldStatus.ts
  src/components/common/formField/index.tsx
  src/components/common/formField/type.ts
  src/components/manage-group/ManageGroup.tsx
  src/components/manage-group/group-validate.ts
  src/components/manage-group/useManageGroup.ts
  src/constants/default-image.ts
  src/constants/paths/index.ts
  src/lib/api/image/postImageUrl.ts
Labels: feat

#74 Feat : create detail Task
  public/icons/doneCheck.icon.svg
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateWiseTaskLists.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/CommentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/DetailTaskCommentsField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/DetailTaskContentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/EditCommentInput.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/index.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/CreateTaskListModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveCommentModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModalContent.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModalPopUp.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TaskListWiseTasks.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TasksWiseTask.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/types/task-list-page-type.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/utils/task-handlers.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/utils/todo-list-item-handlers.ts
  src/app/(content-layout)/[groupId]/tasklist/page.tsx
  src/app/(content-layout)/myhistory/_myhistory/components/GroupedByDateTaskItem.tsx
  src/app/(content-layout)/myhistory/_myhistory/types/myhistory-page-type.ts
  src/assets/Check.tsx
  src/assets/CommentSlot.tsx
  src/components/comment/CommentItemDropdown.tsx
  src/components/comment/index.tsx
  src/components/common/formField/index.tsx
  src/components/profile-badge/index.tsx
  src/components/task-list-item/TaskListItem.tsx
Labels: feat, style

#77 Feat : reset password page UI
  src/app/(form-layout)/reset-password/_reset-password/components/ResetPasswordForm.tsx
  src/app/(form-layout)/reset-password/page.tsx
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/app/globals.css
  src/utils/use-password-visibility.ts
Labels: feat

#76 Feature : 홈페이지 시작 버튼
  src/app/(content-layout)/[groupId]/page.tsx
  src/app/(content-layout)/nogroup/page.tsx
  src/app/_home/StartButton.tsx
  src/app/page.tsx
  src/constants/paths/index.ts
  src/types/group.ts
  src/types/user.d.ts
  src/types/user.ts
Labels: feat

#73 Feat : gnb: 헤더 팀 드롭다운 및 유저 정보/로그아웃 기능 구현
  src/components/common/dropdown/GroupsItem.tsx
  src/components/common/dropdown/ProfileItem.tsx
  src/components/layout/gnb/Header.tsx
  src/components/layout/gnb/SideMenu.tsx
  src/constants/paths/index.ts
  src/lib/cookie/client.ts
Labels: feat

#78 Feat : create report component in [groupId] page
  public/icons/groupIdPage/done-task-icon.svg
  public/icons/groupIdPage/total-task-icon.svg
  src/app/(content-layout)/[groupId]/_[groupId]/Report/GroupProgress.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Report/TaskCount.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Report/index.tsx
  src/app/globals.css
  src/assets/CircularProgress.tsx
Labels: feat

#79 Feat: OAuth kakao
  next.config.ts
  public/icons/google-oauth-icon.svg
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateWiseTaskLists.tsx
  src/app/(form-layout)/editgroup/page.tsx
  src/app/(form-layout)/login/_login/LoginForm.tsx
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/app/oauth/kakao/_kakao/OAuthClient.tsx
  src/app/oauth/kakao/page.tsx
  src/components/common/ErrorModal/index.tsx
  src/components/layout/gnb/Header.tsx
  src/components/manage-group/ManageGroup.tsx
  src/components/manage-group/useManageGroup.ts
  src/components/oauth/OAuthBtnGroup.tsx
  src/constants/default-image.ts
Labels: feat

#82 Refactor : 이전 리뷰 반영 detail-task (list-page)
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateWiseTaskLists.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/DetailTaskCommentsField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/DetailTaskContentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/index.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TasksWiseTask.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/hooks/use-task-actions.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/hooks/use-task-modals.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/types/member-type.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/types/task-type.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/utils/task-handlers.ts
  src/assets/CommentSubmit.tsx
  src/components/task-list-item/TaskListItem.tsx
Labels: chore, refactor

#84 Feat : Group page의 tasklists 섹션 컴포넌트
  public/icons/progress-done-icon.svg
  src/app/(content-layout)/[groupId]/_[groupId]/Tasklists/TasklistItem.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Tasklists/TasklistItemDropdown.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Tasklists/TasklistProgressBadge.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Tasklists/index.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/CreateTaskListModal.tsx
  src/types/task.ts
  src/types/tasklist.ts
  src/types/user.ts
Labels: feat

#85 Feat : Group page의 members 섹션 컴포넌트
  src/app/(content-layout)/[groupId]/_[groupId]/Members/MemberDetailModal.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Members/MemberInvitationModal.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Members/MemberItem.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Members/MemberRemovalModal.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Members/index.tsx
  src/types/user.ts
Labels: feat

#86 Feature : 홈페이지(랜딩페이지) 구현
  public/icons/done-icon.svg
  public/icons/folder-icon.svg
  public/icons/message-icon.svg
  public/icons/repair-icon.svg
  public/images/landing-bottom-lg.png
  public/images/landing-bottom-md.png
  public/images/landing-bottom-sm.png
  public/images/landing-main-lg.png
  public/images/landing-main-md.png
  public/images/landing-main-sm.png
  public/images/landing-mockup1.png
  public/images/landing-mockup2.png
  public/images/landing-mockup3.png
  src/app/_home/BackgroundImage.tsx
  src/app/_home/StartButton.tsx
  src/app/page.tsx
  src/components/layout/gnb/Header.tsx
Labels: feat

#87 Feat : Signup page: 회원가입 유효성 검사 및 모달 UI 개선
  public/icons/hello.svg
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/app/globals.css
  src/components/signup-alert-modal/SignupFailModal.tsx
  src/components/signup-alert-modal/SignupSuccessModal.tsx
  src/constants/messages/signup.ts
  src/utils/validators.ts
Labels: feat

#88 Fix : 홈페이지 스타일 오류 수정 + <img/> Lint 경고 해결 (간단한 수정입니다.)
  src/app/(content-layout)/[groupId]/_[groupId]/Members/MemberDetailModal.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Members/MemberItem.tsx
  src/app/page.tsx
Labels: fix

#89 Feat : manage task item modal
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateWiseTaskLists.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TasksWiseTask.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/manage-task-item-modal/MangeTaskItemModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/types/task-type.ts
  src/app/(content-layout)/[groupId]/tasklist/page.tsx
  src/app/layout.tsx
  src/components/calendar/CalendarSelect.tsx
  src/components/calendar/style.css
  src/components/common/Button/style.ts
  src/components/manage-task-item/components/ManageTaskItem.tsx
  src/components/manage-task-item/components/TimePicker.tsx
  src/components/manage-task-item/components/WeeklySelect.tsx
  src/components/manage-task-item/time-table.ts
  src/components/manage-task-item/type.ts
  src/components/manage-task-item/useManageTaskItem.ts
  src/components/manage-task-modal/ManageTaskModal.tsx
Labels: feat

#90 Fix : form field isSubmit props
  src/components/common/formField/hook/useFieldStatus.ts
  src/components/common/formField/index.tsx
  src/components/common/formField/type.ts
Labels: fix

#97 Feat : group page UI + 멤버 삭제 기능 추가
  public/icons/gear-icon.svg
  public/images/group-thumbnail.png
  src/app/(content-layout)/[groupId]/_[groupId]/Members/MemberDetailModal.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Members/MemberItem.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Members/MemberRemovalModal.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Members/actions.ts
  src/app/(content-layout)/[groupId]/_[groupId]/Members/index.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Report/index.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Tasklists/TasklistItem.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Tasklists/index.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/taskUtils.ts
  src/app/(content-layout)/[groupId]/loading.tsx
  src/app/(content-layout)/[groupId]/page.tsx
  src/app/_home/StartButton.tsx
  src/app/favicon.ico
  src/constants/paths/index.ts
  src/types/group.ts
Labels: feat

#94 Refactor : error.tsx 생성, 에러 바운더리설정
  package-lock.json
  package.json
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateWiseTaskLists.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/CommentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/DetailTaskCommentsField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/DetailTaskContentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/EditCommentInput.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DetailTask/index.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveCommentModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TasksWiseTask.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/hooks/use-task-actions.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/types/task-type.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/utils/format-repeat-schedule.ts
  src/app/(content-layout)/[groupId]/tasklist/error.tsx
  src/app/(content-layout)/[groupId]/tasklist/page.tsx
  src/app/globals.css
  src/app/oauth/kakao/_kakao/OAuthClient.tsx
  src/components/common/ErrorModal/index.tsx
  src/components/task-list-item/TaskListItem.tsx
  src/constants/modal-id/error-modal.ts
Labels: refactor

#96 Feat : reset password page 리퀘스트, 에러 핸들링
  eslint.config.mjs
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveCommentModal.tsx
  src/app/(form-layout)/login/_login/LoginForm.tsx
  src/app/(form-layout)/login/_login/SendResetPassword.tsx
  src/app/(form-layout)/reset-password/_reset-password/components/ResetPasswordForm.tsx
  src/app/(form-layout)/reset-password/_reset-password/types/form-data-type.ts
  src/app/(form-layout)/reset-password/_reset-password/utils/submit-reset-password.ts
  src/app/(form-layout)/reset-password/error.tsx
  src/app/(form-layout)/reset-password/page.tsx
  src/components/common/formField/compound/Input.tsx
  src/components/common/formField/type.ts
Labels: chore, feat

#101 Fix : 디테일 태스크에서 모달 영역 클릭시 디테일 태스크가 닫히던 오류 해결
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/CommentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/DetailTaskCommentsField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/DetailTaskContentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/EditCommentInput.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/page.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TasksWiseTask.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/hooks/use-task-modals.ts
  src/app/(content-layout)/[groupId]/tasklist/layout.tsx
Labels: fix

#99 Feat : manage group page
  next.config.ts
  src/app/(content-layout)/[groupId]/editgroup/page.tsx
  src/app/(form-layout)/addgroup/page.tsx
  src/app/(form-layout)/editgroup/page.tsx
  src/assets/TrashCan.tsx
  src/components/common/formField/index.tsx
  src/components/manage-group/ManageGroup.tsx
  src/components/manage-group/action.ts
  src/components/manage-group/group-validate.ts
  src/components/manage-group/useManageGroup.ts
  src/utils/validators.ts
Labels: feat

#100 Feat : Header: 컴포넌트 분리 등 리팩토링
  public/icons/search.svg
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/components/common/dropdown/GroupsItem.tsx
  src/components/layout/gnb/GroupDropdownSelector.tsx
  src/components/layout/gnb/Header.tsx
  src/components/layout/gnb/ProfileDropdownButton.tsx
  src/components/layout/gnb/SideMenu.tsx
  src/constants/messages/signup.ts
  src/middleware.ts
Labels: refactor

#102 Feat : articles/page: 페이지 UI
  public/icons/full-heart.svg
  public/icons/heart.svg
  public/icons/medal.svg
  src/app/(content-layout)/articles/_articles/components/ArticleOptionsDropdown.tsx
  src/app/(content-layout)/articles/_articles/components/ArticleSearchBar.tsx
  src/app/(content-layout)/articles/_articles/components/BestCard.tsx
  src/app/(content-layout)/articles/_articles/components/Card.tsx
  src/app/(content-layout)/articles/_articles/components/HeartIcon.tsx
  src/app/(content-layout)/articles/_articles/components/LikeToggleButton.tsx
  src/app/(content-layout)/articles/_articles/components/SortToggle.tsx
  src/app/(content-layout)/articles/page.tsx
  src/components/signup-alert-modal/SignupFailModal.tsx
  src/components/signup-alert-modal/SignupSuccessModal.tsx
  src/types/article.ts
Labels: feat

#103 Feat : delete group
  src/app/(content-layout)/[groupId]/editgroup/_editgroup/DeleteGroupButton.tsx
  src/app/(content-layout)/[groupId]/editgroup/action.ts
  src/app/(content-layout)/[groupId]/editgroup/page.tsx
  src/app/(content-layout)/[groupId]/page.tsx
  src/components/DangerModal/index.tsx
  src/components/manage-group/ManageGroup.tsx
  src/components/manage-group/useManageGroup.ts
Labels: feat

#105 Fix : 서버에서 토큰 재발급 안되는 오류 수정
  src/lib/axiosClient.ts
  src/lib/axiosServer.ts
  src/lib/cookie/server.ts
Labels: fix

#106 Feat : 그룹 페이지 할 일 목록 추가 기능
  src/app/(content-layout)/[groupId]/_[groupId]/Tasklists/TasklistAdditionModal.tsx
  src/app/(content-layout)/[groupId]/_[groupId]/Tasklists/actions.ts
  src/app/(content-layout)/[groupId]/_[groupId]/Tasklists/index.tsx
Labels: feat

#107 Feat : nogroup page
  public/images/nogroup-main.png
  src/app/(content-layout)/nogroup/loading.tsx
  src/app/(content-layout)/nogroup/page.tsx
  src/app/(form-layout)/joingroup/page.tsx
  src/constants/paths/index.ts
Labels: feat

#108 Refactor : 디테일 태스크의 에러 바운더리를 위한 구조변경, +할일 추가 버튼 위치 조정
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/CommentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/DetailTask.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/page.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateWiseTaskLists.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TasksWiseTask.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/manage-task-item-modal/MangeTaskItemModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/hooks/use-task-actions.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/hooks/use-task-modals.ts
  src/app/(content-layout)/[groupId]/tasklist/page.tsx
  src/app/(content-layout)/layout.tsx
  src/app/(form-layout)/addgroup/page.tsx
Labels: style, refactor

#111 Refactor : 계정관리페이지 UI 리팩토링 및 사용자 알림 개선
  src/app/mypage/_mypage/NicknameField.tsx
  src/app/mypage/_mypage/PasswordField.tsx
  src/app/mypage/_mypage/ProfileImageUploader.tsx
  src/app/mypage/page.tsx
  src/components/common/modal/ui/ModalOverlay.tsx
  src/components/mypage-modal/ChangePasswordModal.tsx
  src/components/mypage-modal/ConfirmDeleteAccountModal.tsx
  src/components/mypage-modal/DeleteAccountModal.tsx
  src/constants/messages/signup.ts
Labels: refactor

#115 Refactor : 리스트 페이지 스켈레톤
  src/app/(content-layout)/[groupId]/tasklist/(tasklist)/layout.tsx
  src/app/(content-layout)/[groupId]/tasklist/(tasklist)/loading.tsx
  src/app/(content-layout)/[groupId]/tasklist/(tasklist)/page.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/CommentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/DetailTaskCommentsField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/EditCommentInput.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/Skeleton.tsx
  src/assets/CommentSubmit.tsx
Labels: refactor

#109 Feat : detail article UI
  src/app/(content-layout)/articles/[articleId]/_articleId/CommentField.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/CommentList.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/DetailArticleInfo.tsx
  src/app/(content-layout)/articles/[articleId]/page.tsx
  src/app/(content-layout)/articles/_articles/components/LikeToggleButton.tsx
  src/components/profile-badge/index.tsx
Labels: feat

#112 Feat : 팀 참여하기 페이지: 참여기능 및 성공 후 페이지 이동처리
  src/app/(form-layout)/joingroup/page.tsx
  src/components/layout/gnb/Header.tsx
  src/components/signup-alert-modal/SignupSuccessModal.tsx
Labels: feat

#110 Feat : article 작성 페이지
  src/app/(content-layout)/articles/new/page.tsx
  src/app/(content-layout)/articles/page.tsx
  src/constants/paths/index.ts
Labels: feat

#114 Feature : docker setup
  Dockerfile
  next.config.ts
  src/lib/axiosServer.ts
Labels: feat

#118 Ci : dev
  .github/workflows/dev.yml
  Dockerfile
Labels: feat

#119 Refactor : reset password page 리팩토링
  src/app/(form-layout)/login/_login/SendResetPassword.tsx
  src/app/(form-layout)/reset-password/_reset-password/components/ResetPasswordForm.tsx
  src/app/(form-layout)/reset-password/error.tsx
  src/constants/messages/signup.ts
  src/middleware.ts
Labels: refactor

#120 Feat : Articles page: 데이터 패칭
  src/app/(content-layout)/articles/[articleId]/_articleId/DetailArticleInfo.tsx
  src/app/(content-layout)/articles/_articles/components/ArticleOptionsDropdown.tsx
  src/app/(content-layout)/articles/_articles/components/BestCard.tsx
  src/app/(content-layout)/articles/_articles/components/Card.tsx
  src/app/(content-layout)/articles/_articles/components/LikeToggleButton.tsx
  src/app/(content-layout)/articles/_articles/components/Pagination.tsx
  src/app/(content-layout)/articles/page.tsx
  src/assets/HeartIcon.tsx
  src/components/layout/gnb/Header.tsx
  src/types/article.ts
Labels: feat

#123 Feat & Refactor : manage task item modal
  src/app/(content-layout)/[groupId]/editgroup/_editgroup/DeleteGroupButton.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TasksWiseTask.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/manage-task-item-modal/MangeTaskItemModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/types/task-type.ts
  src/components/danger-modal/index.tsx
  src/components/manage-task-item/components/Frequency.tsx
  src/components/manage-task-item/components/ManageTaskItem.tsx
  src/components/manage-task-item/time-table.ts
  src/components/manage-task-item/type.ts
  src/components/manage-task-item/useManageTaskItem.ts
  src/components/task-list-item/TaskListItem.tsx
  src/lib/api/detail-task-item/index.ts
Labels: feat, refactor

#124 Feat : dnd-kit로 할일 순서 바꾸는 기능 구현
  package-lock.json
  package.json
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateWiseTaskLists.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TasksWiseTask.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/hooks/use-dnd-kit.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/hooks/use-task-actions.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/lib/dnd-kit/handlers.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/lib/dnd-kit/sensor.ts
Labels: feat

#130 Refactor : user 데이터 전역 상태로 관리
  src/api/user.ts
  src/app/(form-layout)/login/_login/LoginForm.tsx
  src/app/_home/StartButton.tsx
  src/app/layout.tsx
  src/components/common/spinner/index.tsx
  src/components/mypage-modal/ConfirmDeleteAccountModal.tsx
  src/contexts/UserContext.tsx
Labels: refactor

#132 Feat : not found & bouncing dots loader
  src/app/_home/StartButton.tsx
  src/app/not-found.tsx
  src/components/common/Button/style.ts
  src/components/common/loading/BouncingDots.tsx
  src/components/common/loading/Spiner.tsx
Labels: feat

#129 Feat : detail article data fetching
  src/app/(content-layout)/articles/[articleId]/_articleId/CommentField.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/CommentList.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/DetailArticleInfo.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/action.ts
  src/app/(content-layout)/articles/[articleId]/_articleId/components/CommentField.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/CommentList.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/DetailArticleInfo.tsx
  src/app/(content-layout)/articles/[articleId]/page.tsx
  src/components/comment/CommentItemDropdown.tsx
  src/components/comment/index.tsx
  src/components/common/loading/BouncingDots.tsx
  src/components/danger-modal/index.tsx
  src/components/layout/gnb/SideMenu.tsx
  src/components/profile-badge/index.tsx
Labels: feat

#131 Feat : 자유게시판 페이지 리팩토링
  public/icons/plus.svg
  src/app/(content-layout)/articles/ArticlesPageClient.tsx
  src/app/(content-layout)/articles/_articles/components/ArticleOptionsDropdown.tsx
  src/app/(content-layout)/articles/_articles/components/ArticleSearchBar.tsx
  src/app/(content-layout)/articles/_articles/components/BestCard.tsx
  src/app/(content-layout)/articles/_articles/components/Card.tsx
  src/app/(content-layout)/articles/_articles/components/LikeToggleButton.tsx
  src/app/(content-layout)/articles/_articles/components/Skeleton.tsx
  src/app/(content-layout)/articles/page.tsx
  src/components/layout/gnb/Header.tsx
  src/components/mypage-modal/ChangePasswordModal.tsx
Labels: refactor

#134 Refactor : toastify
  src/components/common/Toastify/ToasProvider.tsx
  src/components/common/Toastify/style.css
Labels: refactor

#139 Fix : Group 페이지
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Members/MemberDetailModal.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Members/index.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Tasklists/TasklistCreateModal.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Tasklists/TasklistItem.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Tasklists/TasklistItemDropdown.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Tasklists/index.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Tasklists/useTasklists.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Title.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/actions.ts
  src/app/(content-layout)/[groupId]/(groupId)/page.tsx
Labels: fix

#141 Refactor : manage group
  src/app/(content-layout)/[groupId]/editgroup/_editgroup/DeleteGroupButton.tsx
  src/components/common/Button/style.ts
  src/components/common/formField/compound/ImageUploader.tsx
  src/components/danger-modal/index.tsx
  src/components/manage-group/ManageGroup.tsx
  src/components/manage-group/useManageGroup.ts
Labels: refactor

#143 Chore : reset password page 에 로딩 스피너, 바운싱도트 적용
  src/app/(form-layout)/login/_login/SendResetPassword.tsx
  src/app/(form-layout)/reset-password/_reset-password/components/ResetPasswordForm.tsx
  src/app/(form-layout)/reset-password/page.tsx
Labels: chore

#145 Refactor : Signup Page: 자동 로그인 로직 개선
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/app/(form-layout)/signup/page.tsx
  src/components/signup-alert-modal/SignupSuccessModal.tsx
Labels: refactor

#147 Feat : article comment infinite scroll & root loading
  package-lock.json
  package.json
  src/app/(content-layout)/articles/[articleId]/_articleId/action.ts
  src/app/(content-layout)/articles/[articleId]/_articleId/components/CommentList.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/ScrollTopButton.tsx
  src/app/(content-layout)/articles/[articleId]/page.tsx
  src/app/(content-layout)/articles/_articles/components/LikeToggleButton.tsx
  src/app/(content-layout)/layout.tsx
  src/app/loading.tsx
  src/assets/HeartIcon.tsx
  src/components/comment/types.d.ts
  src/components/common/loading/BouncingDots.tsx
Labels: feat

#152 Fix : tasklist
  .github/workflows/prod.yml
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Members/MemberItem.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Members/index.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Tasklists/TasklistItem.tsx
  src/app/(content-layout)/[groupId]/(groupId)/page.tsx
  src/app/(content-layout)/articles/[articleId]/edit/page.tsx
  src/app/(content-layout)/articles/new/page.tsx
  src/components/common/loading/Spinner.tsx
  src/components/manage-task-item/components/ManageTaskItem.tsx
  src/constants/paths/index.ts
  src/types/utils.ts
Labels: fix

#151 Refactor : global-refactor
  next.config.ts
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Tasklists/TasklistItemDropdown.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/CommentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/DetailTaskCommentsField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/DetailTaskContentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateSwitcher.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/CreateTaskListModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveCommentModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/utils/format-repeat-schedule.ts
  src/app/(content-layout)/articles/ArticlesPageClient.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/DetailArticleInfo.tsx
  src/app/(content-layout)/articles/[articleId]/edit/page.tsx
  src/app/(content-layout)/articles/_articles/components/LikeToggleButton.tsx
  src/app/(content-layout)/articles/new/page.tsx
  src/app/(form-layout)/joingroup/page.tsx
  src/app/(form-layout)/login/_login/SendResetPassword.tsx
  src/app/(form-layout)/reset-password/_reset-password/components/ResetPasswordForm.tsx
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/app/mypage/_mypage/ProfileImageUploader.tsx
  src/app/mypage/page.tsx
  src/app/oauth/kakao/_kakao/OAuthClient.tsx
  src/components/comment/CommentItemDropdown.tsx
  src/components/layout/gnb/Header.tsx
  src/components/mypage-modal/ChangePasswordModal.tsx
  src/components/mypage-modal/ConfirmDeleteAccountModal.tsx
  src/components/task-list-item/TaskListItem.tsx
Labels: refactor

#146 Refactor : MyPage,Header : 그룹 선택 개선 등 리팩토링
  src/app/mypage/MypageClient.tsx
  src/app/mypage/_mypage/NicknameField.tsx
  src/app/mypage/_mypage/ProfileImageUploader.tsx
  src/app/mypage/_mypage/action.ts
  src/app/mypage/_mypage/mypage-modal/ChangePasswordModal.tsx
  src/app/mypage/_mypage/mypage-modal/ConfirmDeleteAccountModal.tsx
  src/app/mypage/_mypage/mypage-modal/DeleteAccountModal.tsx
  src/app/mypage/page.tsx
  src/components/common/dropdown/OptionSelector.tsx
  src/components/layout/gnb/GroupDropdownSelector.tsx
  src/components/layout/gnb/Header.tsx
  src/components/manage-group/useManageGroup.ts
  src/contexts/UserContext.tsx
Labels: refactor

#156 Fix : ArticlesPage: 내 게시글 보기에서 게시글 없을 경우 페이지네이션 숨김 처리
  src/app/(content-layout)/articles/ArticlesPageClient.tsx
Labels: fix

#154 Feat : manage article
  src/app/(content-layout)/articles/[articleId]/_articleId/components/DetailArticleDropdown.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/DetailArticleInfo.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/ScrollTopButton.tsx
  src/app/layout.tsx
Labels: feat

#157 Build : 5월 25일 일요일
  .github/workflows/prod.yml
  next.config.ts
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Members/MemberItem.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Members/index.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Tasklists/TasklistItem.tsx
  src/app/(content-layout)/[groupId]/(groupId)/_[groupId]/Tasklists/TasklistItemDropdown.tsx
  src/app/(content-layout)/[groupId]/(groupId)/page.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/CommentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/DetailTaskCommentsField.tsx
  src/app/(content-layout)/[groupId]/tasklist/@detailTask/_components/DetailTaskContentField.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateSwitcher.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/CreateTaskListModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveCommentModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/utils/format-repeat-schedule.ts
  src/app/(content-layout)/articles/ArticlesPageClient.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/DetailArticleDropdown.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/DetailArticleInfo.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/ScrollTopButton.tsx
  src/app/(content-layout)/articles/[articleId]/edit/page.tsx
  src/app/(content-layout)/articles/_articles/components/LikeToggleButton.tsx
  src/app/(content-layout)/articles/new/page.tsx
  src/app/(form-layout)/joingroup/page.tsx
  src/app/(form-layout)/login/_login/SendResetPassword.tsx
  src/app/(form-layout)/reset-password/_reset-password/components/ResetPasswordForm.tsx
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/mypage/MypageClient.tsx
  src/app/mypage/_mypage/NicknameField.tsx
  src/app/mypage/_mypage/ProfileImageUploader.tsx
  src/app/mypage/_mypage/action.ts
  src/app/mypage/_mypage/mypage-modal/ChangePasswordModal.tsx
  src/app/mypage/_mypage/mypage-modal/ConfirmDeleteAccountModal.tsx
  src/app/mypage/_mypage/mypage-modal/DeleteAccountModal.tsx
  src/app/mypage/page.tsx
  src/app/oauth/kakao/_kakao/OAuthClient.tsx
  src/components/comment/CommentItemDropdown.tsx
  src/components/common/dropdown/OptionSelector.tsx
  src/components/common/loading/Spinner.tsx
  src/components/layout/gnb/GroupDropdownSelector.tsx
  src/components/layout/gnb/Header.tsx
  src/components/manage-group/useManageGroup.ts
  src/components/manage-task-item/components/ManageTaskItem.tsx
  src/components/signup-alert-modal/SignupSuccessModal.tsx
  src/components/task-list-item/TaskListItem.tsx
  src/constants/paths/index.ts
  src/contexts/UserContext.tsx
  src/types/utils.ts
Labels: build

#158 Style : ArticlesPage: 글쓰기 버튼 위치 수정
  src/app/(content-layout)/articles/ArticlesPageClient.tsx
Labels: style

#162 Refactor : manage task item & group
  src/app/(content-layout)/[groupId]/editgroup/_editgroup/DeleteGroupButton.tsx
  src/components/comment/CommentItemDropdown.tsx
  src/components/manage-task-item/useManageTaskItem.ts
  src/components/task-list-item/TaskListItem.tsx
Labels: refactor

#163 Fix : Header: 드롭다운 실시간 반영 수정
  src/app/(content-layout)/[groupId]/editgroup/_editgroup/DeleteGroupButton.tsx
  src/app/(content-layout)/articles/ArticlesPageClient.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/DetailArticleInfo.tsx
  src/app/(content-layout)/articles/_articles/components/Card.tsx
  src/app/(content-layout)/articles/_articles/components/Skeleton.tsx
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/app/_home/StartButton.tsx
  src/components/layout/gnb/Header.tsx
  src/components/manage-group/useManageGroup.ts
Labels: fix

#165 Fix : 팀 참여하기 페이지에서 UserContext 적용하여 사용자 이메일 처리 개선
  src/app/(form-layout)/joingroup/page.tsx
Labels: fix

#164 Refactor : manage group
  src/components/manage-group/ManageGroup.tsx
  src/components/manage-group/useManageGroup.ts
Labels: refactor

#166 Build : for demo day
  src/app/(content-layout)/[groupId]/editgroup/_editgroup/DeleteGroupButton.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/Skeleton.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/Tasks.tsx
  src/app/(content-layout)/articles/ArticlesPageClient.tsx
  src/app/(content-layout)/articles/[articleId]/_articleId/components/DetailArticleInfo.tsx
  src/app/(content-layout)/articles/_articles/components/Card.tsx
  src/app/(content-layout)/articles/_articles/components/Skeleton.tsx
  src/app/(content-layout)/myhistory/page.tsx
  src/app/(content-layout)/nogroup/loading.tsx
  src/app/(form-layout)/joingroup/page.tsx
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/app/_home/StartButton.tsx
  src/app/mypage/MypageClient.tsx
  src/app/mypage/_mypage/PasswordField.tsx
  src/app/mypage/_mypage/action.ts
  src/app/mypage/_mypage/mypage-modal/ChangePasswordModal.tsx
  src/app/oauth/kakao/_kakao/OAuthClient.tsx
  src/app/oauth/kakao/page.tsx
  src/app/page.tsx
  src/components/comment/CommentItemDropdown.tsx
  src/components/layout/gnb/Header.tsx
  src/components/manage-group/ManageGroup.tsx
  src/components/manage-group/useManageGroup.ts
  src/components/manage-task-item/useManageTaskItem.ts
  src/components/task-list-item/TaskListItem.tsx
Labels: build

#168 Fix : dnd시 taskListId를 잘못 가져오는 문제 해결
  src/app/(content-layout)/[groupId]/tasklist/(tasklist)/page.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TaskLists.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/Tasks.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/hooks/use-dnd-kit.ts
Labels: fix

#167 Fix : nogroup페이지에서 프로필 드롭다운이 안나오는 문제 수정
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/components/layout/gnb/Header.tsx
Labels: fix
