Repository FE-team1/coworkers, pull requests merged in 2025-04, with the labels that each got.

#2 Chore : edit PR-template
  .github/pull_request_template.md
Labels: chore

#3 Chore : global css 추가
  src/app/globals.css
Labels: style

#4 Feat : create selected dropDown & base dropDown
  next.config.ts
  public/icons/dropdown-icon.svg
  public/icons/kebab-icon.svg
  src/app/globals.css
  src/app/page.tsx
  src/components/common/dropDown/drop-down.tsx
  src/components/common/dropDown/groups-item.tsx
  src/components/common/dropDown/profile-item.tsx
  src/types/global.d.ts
  src/utils/use-outside-click-auto-close.ts
Labels: feat

#10 Feat : input component
  src/components/common/.gitkeep
  src/components/common/input/index.tsx
Labels: feat

#13 Refactor : 기존 dropdown.tsx 리팩토링
  src/components/common/dropDown/GroupsItem.tsx
  src/components/common/dropDown/OptionSelector.tsx
  src/components/common/dropDown/ProfileItem.tsx
  src/components/common/dropDown/index.tsx
  src/types/global.d.ts
Labels: refactor

#16 Feat : textarea component
  package-lock.json
  package.json
  src/components/common/input/index.tsx
  src/components/common/textarea/index.tsx
Labels: feat

#18 Style : position 추가 , scroll 오류 해결
  src/components/common/dropDown/OptionSelector.tsx
  src/components/common/dropDown/index.tsx
Labels: style

#14 Feature: modal UI components
  public/icons/x-icon.svg
  src/app/globals.css
  src/components/common/modal/ModalCloseButton.tsx
  src/components/common/modal/ModalContainer.tsx
  src/components/common/modal/ModalFooter.tsx
  src/components/common/modal/ModalOverlay.tsx
Labels: feat

#15 Feature : create OAuthUI
  public/.gitkeep
  public/icons/google-oauth-icon.svg
  public/icons/kakao-oauth-icon.svg
  src/components/oauth/OAuthBtnGroup.tsx
  src/components/oauth/index.tsx
Labels: feat

#21 Style : position props -> placement로 수정
  src/components/common/dropDown/OptionSelector.tsx
  src/components/common/dropDown/index.tsx
Labels: style

#26 Chore : dropdown 폴더명 변경 git 폴더명 대소문자 인식
  src/components/common/dropdown/GroupsItem.tsx
  src/components/common/dropdown/OptionSelector.tsx
  src/components/common/dropdown/ProfileItem.tsx
  src/components/common/dropdown/index.tsx
Labels: chore

#27 Chore : Build 오류 해결후 dev 병합
  public/icons/close.svg
  public/icons/gnb-menu.svg
  public/icons/user.svg
  src/app/globals.css
  src/app/page.tsx
  src/assets/logo-lg.svg
  src/assets/logo-sm.svg
  src/components/layout/gnb/Header.tsx
  src/components/layout/gnb/Logo.tsx
  src/components/layout/gnb/SideMenu.tsx
Labels: fix

#22 Style : create (contentPages) & (formPages) directory
  src/app/(content-layout)/layout.tsx
  src/app/(content-layout)/myhistory/page.tsx
  src/app/(form-layout)/layout.tsx
  src/app/(form-layout)/login/page.tsx
Labels: style

#39 Fix : GitHub workflow 설정 파일 정리
  .github/workflows/auto-assign.yml
  .github/workflows/proof-html.yml
Labels: fix

#32 Feature : landing page 기본 시작 버튼 구현, 경로 상수 정의
  src/app/_home/StartButton.tsx
  src/app/page.tsx
  src/constants/paths/index.ts
Labels: feat

#37 Feature : login page
  src/app/(form-layout)/login/_login/LoginForm.tsx
  src/app/(form-layout)/login/_login/login.tsx
  src/app/(form-layout)/login/page.tsx
Labels: feat

#42 Feat : install & update next.config.ts for SVGR
  next.config.ts
  package-lock.json
  package.json
Labels: chore, feat

#43 Refactor : update next.config.ts & svgr.d.ts
  next.config.ts
  src/components/layout/gnb/Logo.tsx
  src/types/svgr.d.ts
  tsconfig.json
Labels: refactor

#44 Feat : button common component
  src/app/globals.css
  src/app/page.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/style.ts
Labels: feat

#45 Style : Header: 드롭다운에 버튼 컴포넌트 적용, 로고 svg 파일 반응형 수정
  public/icons/logo-sm.svg
  src/assets/CoworkersLogo.svg
  src/assets/logo-lg.svg
  src/assets/logo-sm.svg
  src/components/layout/gnb/Header.tsx
  src/components/layout/gnb/Logo.tsx
Labels: style

#46 Feat : file input
  public/icons/circle-pencil.svg
  public/icons/image-icon.svg
  public/icons/user-icon.svg
  src/app/(form-layout)/login/_login/LoginForm.tsx
  src/assets/Plus.tsx
  src/components/common/formField/compound/FileInput.tsx
  src/components/common/formField/compound/UploadImage.tsx
  src/components/common/formField/index.tsx
  src/components/common/formField/type.ts
Labels: feat

#29 Feature : modal 기능 추가
  src/assets/CoworkersLogo.svg
  src/assets/CoworkersLogo.tsx
  src/components/common/modal/ModalCloseButton.tsx
  src/components/common/modal/core/ModalContext.tsx
  src/components/common/modal/core/ModalPortal.tsx
  src/components/common/modal/core/ModalProvider.tsx
  src/components/common/modal/core/useModalContext.tsx
  src/components/common/modal/index.ts
  src/components/common/modal/ui/ModalCloseButton.tsx
  src/components/common/modal/ui/ModalContainer.tsx
  src/components/common/modal/ui/ModalDescription.tsx
  src/components/common/modal/ui/ModalFooter.tsx
  src/components/common/modal/ui/ModalHeading.tsx
  src/components/common/modal/ui/ModalOverlay.tsx
  src/components/common/modal/ui/ModalTrigger.tsx
  src/components/layout/gnb/Logo.tsx
Labels: feat

#49 Feat : Signup page: UI 생성
  src/app/(form-layout)/layout.tsx
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/app/(form-layout)/signup/page.tsx
  src/components/layout/gnb/Header.tsx
  src/utils/validators.ts
Labels: feat

#50 Feature : myhistorypage UI
  src/app/(content-layout)/myhistory/_myhistory/components/GroupedByDateTaskItem.tsx
  src/app/(content-layout)/myhistory/_myhistory/components/GroupedByDateTaskList.tsx
  src/app/(content-layout)/myhistory/_myhistory/myhistory-mock-data.ts
  src/app/(content-layout)/myhistory/_myhistory/types/myhistory-page-type.ts
  src/app/(content-layout)/myhistory/page.tsx
  src/components/task-list-item/TaskListItem.tsx
Labels: feat, style

#52 Refactor : file input
  src/components/common/formField/compound/FileInput.tsx
  src/components/common/formField/compound/ImageUploader.tsx
  src/components/common/formField/index.tsx
  src/components/common/formField/type.ts
Labels: refactor

#57 Feat : team create/edit page
  src/app/(form-layout)/addteam/page.tsx
Labels: feat

#55 Feature : axios 인스턴스 추가
  package-lock.json
  package.json
  src/app/(form-layout)/login/_login/LoginForm.tsx
  src/app/(form-layout)/login/_login/index.tsx
  src/app/page.tsx
  src/lib/axiosClient.ts
  src/lib/axiosServer.ts
  src/lib/cookie/client.ts
  src/lib/cookie/server.ts
Labels: feat

#54 Feat : create list page
  public/icons/next-arrow-icon.svg
  public/icons/prev-arrow-icon.svg
  src/app/(content-layout)/[teamid]/tasklist/_tasklist/components/DateWiseTaskList.tsx
  src/app/(content-layout)/[teamid]/tasklist/_tasklist/components/TaskWiseTodoListItem.tsx
  src/app/(content-layout)/[teamid]/tasklist/_tasklist/mock-data-task-list-page.ts
  src/app/(content-layout)/[teamid]/tasklist/_tasklist/types/task-list-page-type.ts
  src/app/(content-layout)/[teamid]/tasklist/_tasklist/utils/todo-list-item-handlers.ts
  src/app/(content-layout)/[teamid]/tasklist/page.tsx
  src/app/(content-layout)/layout.tsx
  src/components/common/dropdown/index.tsx
  src/components/task-list-item/TaskListItem.tsx
Labels: feat, style

#53 Feat : SignupPage: 유효성 검사 및 에러 메시지 수정
  public/icons/visibility_off.svg
  public/icons/visibility_on.svg
  src/app/(form-layout)/signup/_signup/PasswordToggleButton.tsx
  src/app/(form-layout)/signup/_signup/SignupForm.tsx
  src/utils/validators.ts
Labels: feat

#60 Feat : jointeam page: UI 생성
  src/app/(form-layout)/jointeam/page.tsx
Labels: feat

#61 Feat : manage(create/edit) task modal UI
  package-lock.json
  package.json
  src/components/calendar/CalendarSelect.tsx
  src/components/calendar/style.css
  src/components/common/formField/compound/Textarea.tsx
  src/components/manage-task-modal/ManageTaskModal.tsx
  src/components/manage-task-modal/TimePicker.tsx
  src/components/manage-task-modal/WeeklySelect.tsx
  src/components/manage-task-modal/time-table.ts
Labels: feat

#65 Feat : list page 데이터 패칭 & 모달 컨텐츠 UI
  public/icons/danger.icon.svg
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/DateWiseTaskLists.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/CreateTaskListModal.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModalContent.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/ModalContents/RemoveTaskModalPopUp.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/components/TaskListWiseTasks.tsx
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/types/task-list-page-type.ts
  src/app/(content-layout)/[groupId]/tasklist/_tasklist/utils/todo-list-item-handlers.ts
  src/app/(content-layout)/[groupId]/tasklist/page.tsx
  src/app/(content-layout)/[teamid]/tasklist/_tasklist/components/DateWiseTaskList.tsx
  src/app/(content-layout)/[teamid]/tasklist/_tasklist/mock-data-task-list-page.ts
  src/app/(content-layout)/[teamid]/tasklist/_tasklist/types/task-list-page-type.ts
  src/app/(content-layout)/[teamid]/tasklist/page.tsx
  src/app/layout.tsx
  src/components/common/formField/index.tsx
  src/components/common/formField/style.ts
  src/components/common/formField/type.ts
Labels: feat
